name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  checkout:
    name: Checkout to current repository
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

  push_to_registry:
    name: Push Docker image to Github Registry
    runs-on: ubuntu-20.04
    steps:
      - name: Login to github registry
        run: echo ${{ secrets.DEPLOYMENT_PAT }} | sudo docker login ghcr.io -u ${{ secrets.DEPLOYMENT_USERNAME }} --password-stdin

      - name: Build docker image
        run: make build

      - name: Push docker image
        run: make push
